### ISSUE TITLE
how can i send message through my android phone without using whatsapp

### ISSUE THREAD

**Issue by itclubonline** [amizz/Whatsapp-Direct-Messaging-API#2]

**Comment by amizz** [comment]
It's not possible at the moment. Whatsapp didn't provide any direct API access to allow you to send a message without the app itself.

This API only open Whatsapp app using links.

**Comment by itclubonline** [comment]
oh ok ,
Plz do let us know if anything comes in your way.

Regards
animesh shah
chanakya Software
