### ISSUE TITLE
does not automatically send message

### ISSUE THREAD

**Issue by derit** [amizz/Whatsapp-Direct-Messaging-API#4]
i trying direct send message but it's does automatically send message,
but i must click send button on the browser, i using chrome

**Comment by Amit-Gharu** [comment]
I have to clicking on send button. I want send message automatically.

**Comment by tkovs** [comment]
I'm trying do it

**Comment by tkovs** [comment]
I'm not trying to do this because I decided to use these repositories:

- [whatsapp-web-reveng](https://github.com/sigalor/whatsapp-web-reveng)
- [go-whatsapp](https://github.com/Rhymen/go-whatsapp)
